version: '3.8'

services:
  browser:
    container_name: test-browser
    build: client/
    command: npm run start
    ports:
      - 3010:3010

  api:
    container_name: test-server
    build: api/
    command: npm run start:dev
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=test-postgres

  postgres:
    container_name: test-postgres
    image: postgres:14.1-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ab1f6hh942sm
      POSTGRES_USER: johny_cage
      POSTGRES_DB: test_db
